V 3/Add wui-grid component
WalletConnect/web3modal pull request #1124
Opened 2023-06-30 14:23 UTC by svenvoskamp

# Changes

- feat: Add `wui-grid` component

2023-07-01 05:27 UTC, 0xAsimetriq requested changes
Left one comment, also have you tested all of the properties? I can't seem to get things like column / row gap working for some reason in storybook. Noticed similar on flex element. It could be that it is being overpowered by other styles like gap.

Maybe there is a way in storybook to remove certain properties when others are set to showcase them all?

2023-07-01 05:27 UTC, 0xAsimetriq commented on apps/gallery/utils/PresetUtils.ts
> +  'xxs',
`xxs` looks to be repeated

2023-07-03 09:36 UTC, svenvoskamp commented
- When gap is set, it overrules the `column-gap` and `row-gap`. I've added an `undefined` option in Storybook for spacing properties.
- Removed duplicate value

2023-07-03 09:43 UTC, 0xAsimetriq approved these changes

2023-07-03 09:45 UTC, merged