Feat/ethers disconnect
WalletConnect/web3modal pull request #1444
Opened 2023-11-03 14:30 UTC by svenvoskamp

* Add  function `disconnect` to exports

Closes https://github.com/WalletConnect/web3modal/issues/1439

2023-11-07 09:58 UTC, svenvoskamp commented on packages/ethers5/exports/react.tsx
> +      provider?.emit('disconnect')
This triggers `disconnectHandler` inside the client, which clears `localStorage`

2023-11-07 10:12 UTC, 0xAsimetriq requested changes

2023-11-07 10:12 UTC, 0xAsimetriq commented on packages/ethers5/src/client.ts
> +    const provider = ProviderController.state.provider
```suggestion
    const {provider, providerType} = ProviderController.state
```

2023-11-07 10:12 UTC, 0xAsimetriq commented on packages/ethers5/exports/react.tsx
> +  async function disconnect() {
Let's keep consistent and do `useDisconnect` that returns disconnect function. Also, it seems like same logic as in `client` is replicated there. Can we not just use `ConnectionController.disconnect` at this stage (same as all other hooks use controllers for things like theme etc?)

2023-11-07 10:33 UTC, 0xAsimetriq approved these changes
Much cleaner 👌 ty for changes

2023-11-07 15:13 UTC, glitch-txs approved these changes

2023-11-07 17:17 UTC, merged

2023-11-14 19:09 UTC, GorgeousPuree commented
Please update documentation with this new hook.
https://docs.walletconnect.com/web3modal/react/about