add ethers v6 support
WalletConnect/web3modal pull request #1484
Opened 2023-11-18 00:48 UTC by glitch-txs

# Breaking Changes

ethers v6 package

ethers provider [doesn't allow events from wallet providers](https://github.com/ethers-io/ethers.js/issues/4334), so I'm using the raw providers and then exposing them to the uders, they can alter wrap themselves the raw provider with ethers.

# Changes

- feat: ethers v6 support
![image](https://github.com/WalletConnect/web3modal/assets/66949816/930c2c9c-fbdb-45e8-bbf2-b81a29f1114f)

# Some considerations

There are two things I think we should change in both libraries:

- Disconnect event is used to disconnect the user from the session, this overlaps with the actual use of disconnect following EIP-1193 where it should only be called when the provider is disconnected from the blockchain

- `name` property from EIP-6963 is being used to filter out duplicated providers, we should use uuid instead as some wallets could impersonate each other

2023-11-20 10:16 UTC, svenvoskamp commented on packages/ethers/exports/react.tsx
> +export function useWeb3ModalProvider() {
Shouldn't we add `signer` to export here, same on how we do it in `ethers-5`? 

This way we keep consistency between ethers packages.

2023-11-20 10:17 UTC, svenvoskamp commented on packages/ethers/exports/vue.ts
> +export function useWeb3ModalProvider() {
Same as comment above ^

2023-11-20 10:28 UTC, svenvoskamp commented on packages/ethers/src/utils/constants.ts
We use same `constants` and `helpers` in `ethers` and `ethers-5`. Maybe we can rename `@web3modal/utils` package to `@web3modal/scaffold-utils` and add an ethers specific folder to create shared `constants`, `helpers`, etc

2023-11-20 10:28 UTC, svenvoskamp commented on packages/ethers/src/utils/helpers.ts
Same comments as above ^

2023-11-20 10:29 UTC, svenvoskamp requested changes
Left a few comments and suggestions about duplicate code. Other than that looks good 👍

Can you also fix CI status to green?

2023-11-20 10:45 UTC, ignaciosantise commented on apps/laboratory/package.json
> +    "ethers": "6.8.1"
i think all dev dependencies are added in the project root

2023-11-20 13:21 UTC, glitch-txs commented on packages/ethers/src/utils/constants.ts
I'd suggest creating a global library like @web3modal/connectors or something like that, we can add the whole logic there, then for packages like @web3modal/ethers we can just have the exports there, and pass down to the Web3Modal class the functions needed for fetching data like Balance/ENS. We could eventually easily add web3js support as well.

thoguhts?

2023-11-22 01:46 UTC, glitch-txs commented on packages/ethers/src/utils/constants.ts
Helpers use particular types from ethers v5 library so I wasn't able to move that one

2023-11-22 17:32 UTC, merged