add status
WalletConnect/web3modal pull request #2184
Opened 2024-04-23 21:30 UTC by glitch-txs

# Breaking Changes

N/A

# Changes

- feat: add status state with 'reconnecting', 'connected' and 'disconnected' values.
- fix:
- chore:

# Associated Issues

closes #...

2024-04-24 08:13 UTC, svenvoskamp requested changes
LGTM, but I think there are some linter changes as well because you removed `plugin:prettier/recommended`. Could you resolve that?

2024-05-30 16:04 UTC, tomiir commented on turbo.json
> +        "^build:siwe",
is this ok @glitch-txs ?

2024-05-30 16:28 UTC, glitch-txs commented on turbo.json
> +        "^build:siwe",
yes

2024-05-30 17:33 UTC, svenvoskamp approved these changes

2024-05-30 17:34 UTC, merged