feat: feat: added vue for exports in solana
WalletConnect/web3modal pull request #2449
Opened 2024-06-20 12:18 UTC by phoenixVS

# Breaking Changes

N/A

# Changes

- feat:
- fix:
- chore:

# Associated Issues

closes #...

2024-07-01 08:37 UTC, glitch-txs requested changes

2024-07-01 08:37 UTC, glitch-txs commented on packages/solana/exports/vue.ts
> +import { useSnapshot } from 'valtio'
Valtio is a React dependent package and should not be used here. Check the `scaffold-vue` package please.

2024-07-05 07:47 UTC, enesozturk approved these changes

2024-07-05 10:56 UTC, enesozturk commented on examples/react-solana/src/App.tsx
> +import { WagmiProvider } from 'wagmi'
Do we need wagmi for Solana example?

2024-07-05 10:56 UTC, enesozturk commented on examples/react-solana/src/App.tsx
> +    <WagmiProvider config={wagmiConfig}>
Same, do we need wagmi related setup in this example?

2024-07-05 13:50 UTC, enesozturk commented on examples/react-solana/package.json
> +    "viem": "2.10.3",
Prob we don't need `viem` too.

2024-07-05 13:50 UTC, enesozturk approved these changes

2024-07-05 14:05 UTC, glitch-txs approved these changes

2024-07-07 13:10 UTC, merged