Update Web3Auth to include whitelabel and solana and other chain support
WalletConnect/web3modal pull request #572
Opened 2022-09-09 08:31 UTC by shahbaz17

Hi team,

I am one of the team members from @web3auth and wanted to update the SDK to include the latest changes.

Please take a look.

Thanks.

2022-10-11 20:45 UTC, arein commented
Can you please provide a better description + screenshots

2022-10-20 23:07 UTC, chrischip commented
this is exactly what I need

2022-10-21 13:02 UTC, chrischip commented on src/providers/connectors/web3auth.ts
> +            const appLogo = options.loginMethodsOrder || ""
this line is incorrect....

2022-10-21 13:03 UTC, chrischip requested changes
appLogo not correctly obtained from options

2022-10-25 04:37 UTC, shahbaz17 commented
Hey team,

We recently renamed our `@web3auth/web3auth` SDK to `@web3auth/modal` and added more support. Please check out [here](https://web3auth.io/docs/sdk/web/modal/).

I'll be updating this PR to include the latest changes from https://web3auth.io/docs/sdk/web/modal/

2023-01-21 14:42 UTC, 0xAsimetriq commented
With stable version 2.0.0 of Web3Modal now released, we are officially dropping support for version 1.x
Due to this this issue/pr was marked for closing. It is highly recommended to upgrade as 2.x will be receiving further updates that will enable functionality for some of our newer sdks like auth and push as well as support for WalletConnect v2 (See this post about WalletConnect v1 being deprecated https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e)

If you need to continue using Web3Modal 1.x and require this feature/fix implemented, we suggest adding it via forking V1 branch.

2023-01-21 14:42 UTC, closed without merging